services:
  docs:
    image: my_store_app_local_docs
    container_name: my_store_app_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./my_store_app:/app/my_store_app:z
    ports:
      - '9000:9000'
    command: /start-docs
